### PR TITLE
EC-304: Fixed configuration recipes for Commerce features

### PR DESCRIPTION
**Pull request by alongosz**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EC-304](https://issues.ibexa.co/browse/EC-304)
| **Requires**                            | ibexa/installer#8, ibexa/post-install#3
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no

This PR adds a directory for auto-generated Commerce configuration files. This directory is mapped as a mount point for P.sh to be able to write to it during the deploy phase.

### TODO
- [x] Update P.sh configuration installer

### CODE REVIEW

**Review by Steveb-p — APPROVED** [review]

**Review by mikadamczyk — APPROVED** [review]

**Review by webhdx — APPROVED** [review]
Looks okay. Something to consider: How does it relate to already released 3.3.0? Will it break the recipe for that release? We have to be careful because `3.3` recipe is shared across all 3.3.x released. In case of issues we can create recipe copy in `3.3.0` directory to not touch 3.3.0 tag at all.

**Comment by alongosz** [comment]
> Looks okay. Something to consider: How does it relate to already released 3.3.0? Will it break the recipe for that release? We have to be careful because `3.3` recipe is shared across all 3.3.x released. In case of issues we can create recipe copy in `3.3.0` directory to not touch 3.3.0 tag at all.

Indeed I missed that. After further consideration I believe it should be rather harmless (cc @micszo - maybe some QA for that is needed). Worst case scenario - it would create a directory with no files, which is acceptable since there's asterisk there (I mean AFAIR I tested this w/o any files in that dir yet).

**Comment by micszo** [comment]
Testing discovered: https://issues.ibexa.co/browse/EZEE-3458

**Comment by alongosz** [comment]
Update: added via ba46cf861817f68438757ee50b7e0fa71a9eee6e missing Nelmio Solarium Bundle configuration for Content edition (required to properly display Product Catalog menu).

**Review by micszo — APPROVED** [review]
Retested successfully with Solr on Platform.sh and locally.
Applied the changes to Ibexa Content, Experience and Commerce.
The issue with Content is gone now.

**Pull request merged**
