### PR TITLE
EZEE-3474: standard pagelayout generator meta tag: eZ Platform → Ibexa DXP

### PR DESCRIPTION
**Pull request by adriendupuis**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZEE-3474](https://issues.ibexa.co/browse/EZEE-3474)
| **Type**           | Improvement/Misc
| **Target version** | master (3.3)
| **BC breaks**      | no
| **Doc needed**     | no

Update generator meta from eZ Platform to Ibexa DXP in default pagelayout from standard theme in

- [x] Open Source (oss)
- [x] Content
- [x] Experience
- [x] Commerce

### CODE REVIEW

**Comment by lserwatka** [comment]
We need a JIRA ticket for this, and PR should follow our standards.

**Comment by adriendupuis** [comment]
> We need a JIRA ticket for this, and PR should follow our standards.

@lserwatka I opened the JIRA ticket. I didn't find the PR template on this project so I improvised a description from a previous PR from another repo. What are standards not followed yet?

**Comment by lserwatka** [comment]
Only PR title is wrong. It should start from EZEE-3474:

**Comment by lserwatka** [comment]
Any reason why you keep it as a draft?

**Comment by adriendupuis** [comment]
> Any reason why you keep it as a draft?

@lserwatka None. Just forgot to set it as ready after last commit.

**Review by lserwatka — APPROVED** [review]

**Pull request merged**
